config_from_cf:
  cf_deployment_name: (( merge ))
  cf_director_uuid: (( merge ))
  nats:
    user: (( merge ))
    password: (( merge ))
    port: (( merge ))
    machines: (( merge ))
  system_domain: (( merge ))
  app_domains: (( merge ))
  api_url: (( merge ))
  skip_ssl_validation: (( merge ))
  smoke_tests:
    use_existing_org: (( merge ))
    org: (( merge ))
  uaa:
    scim:
      users: (( merge ))
  consul:
    datacenter: (( merge ))
    domain: (( merge ))
    log_level: (( merge ))
    lan_servers: (( merge ))
    ca_cert: (( merge ))
    agent_cert: (( merge ))
    agent_key: (( merge ))
    encrypt_keys: (( merge ))
    server_cert: (( merge ))
    server_key: (( merge ))
